### ISSUE TITLE
Adding a pattern for PhoneNumber in /verify

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/NumberVerification#76]
**Problem description**
Currently the phoneNumber is not validated against a pattern.

**Possible evolution**

Add the following pattern to "phoneNumber":

```
pattern: '^\+?[0-9]{5,15}$'
```

```yaml
    NumberVerificationRequestBody:
      type: object
      description: Payload to verify the phone number.
      minProperties: 1
      maxProperties: 1
      properties:
        phoneNumber:
          description: A phone number belonging to the user in **E.164 format (starting with country code)**. Optionally prefixed with '+'.
          type: string
          example: '+346661113334'
          pattern: '^\+?[0-9]{5,15}$'
      (...) 
```
