### ISSUE TITLE
Update the "server"-section to align with other CAMARA specifications

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/NumberVerification#77]
**Problem description**
Some changes would align with other specifications, such as e.g. DeviceLocation.

```yaml
servers:
  - url: https://{host}{basePath}
    variables:
      host:
        default: api.example.com
        description: Host that serves the API
      basePath:
        default: /number-verification/v0
        description: Base path for the number verification API
```

**Expected behavior**
```yaml
servers:
  - url: '{apiRoot}/number-verification/v0'
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
```

**Additional context**
Reference to other specifications:

- DeviceLocation Retrieval: https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/location-retrieval.yaml
- DeviceStatus: https://github.com/camaraproject/DeviceStatus/blob/v0.5.0-rc/code/API_definitions/device-status.yaml
